export const SET_USER = 'SET_USER';
export const SET_ID_TOKEN = 'SET_ID_TOKEN';

export const SET_MESSAGE = 'SET_MESSAGE';

export const ADD_FILE_UPLOAD = 'ADD_FILE_UPLOAD';
export const DELETE_FILES = 'DELETE_FILES';
export const DELETE_FILE_UPLOAD = 'DELETE_FILE_UPLOAD';
export const RECEIVE_FILES = 'RECEIVE_FILES';
export const RECEIVE_POST_FILE = 'RECEIVE_POST_FILE';
export const UPDATE_FILE_UPLOAD = 'UPDATE_FILE_UPLOAD';
export const RECEIVE_PATCH_FILE = 'RECEIVE_PATCH_FILE';

export const RECEIVE_USERS = 'RECEIVE_USERS';

export const RECEIVE_GET_BUILDINGS = 'RECEIVE_GET_BUILDINGS';
export const RECEIVE_POST_BUILDING = 'RECEIVE_POST_BUILDING';
